function [result] = overlapping(coord1, coord2, siz)
  rect = javaObject('java.awt.Rectangle',...
                    coord1(1), coord1(2),...
                    siz(1) * coord1(3), siz(2) * coord1(3));
  result = rect.intersects(coord2(1), coord2(2),...
                           siz(1) * coord2(3), siz(2) * coord2(3));
end